media:
  input: images
  output: /images
  path: images
  categories: [image]
content:
  - name: pages
    label: Pages
    path: pages
    type: collection
    subfolders: false
    view:
      fields: [permalink, meta_title, header_text]
      primary: header_text
      sort: [header_text]
    fields:
      - { name: header_image, type: image, label: Header Image }
      - { name: header_text, type: string, label: Header Text }
      - { name: subtitle, type: string, label: Subtitle }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, type: string }
          - { name: order, type: number }
          - { name: url, type: string }
      - { name: layout, type: string }
      - { name: permalink, type: string }
  - name: news
    label: News
    path: news
    type: collection
    subfolders: false
    fields:
      - { name: title, type: string, label: Title }
      - { name: header_image, type: image, label: Header Image }
      - { name: date, label: Date, type: date }
      - { name: subtitle, type: string, label: Subtitle }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - { name: header_text, type: string, label: Header Text }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
  - name: products
    label: Products
    path: products
    type: collection
    subfolders: false
    fields:
      - { name: title, type: string, label: Title }
      - { name: header_image, type: image, label: Header Image }
      - name: categories
        label: Categories
        type: reference
        options:
          collection: categories
          multiple: true
          search: "title"
          value: "{path}"
          label: "{title}"
      - { name: price, label: Price, type: string }
      - { name: etsy_url, label: Etsy URL, type: string }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - { name: features, type: string, label: Features, list: true }
      - name: gallery
        type: image
        label: Gallery
        options: { multiple: true }
      - { name: header_text, type: string, label: Header Text }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - { name: subtitle, type: string, label: Subtitle }
  - name: categories
    label: Categories
    path: categories
    type: collection
    subfolders: false
    filename: "{primary}.md"
    fields:
      - { name: title, type: string, label: Title }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - { name: featured, label: Featured, type: boolean }
      - { name: header_image, type: image, label: Header Image }
      - { name: header_text, type: string, label: Header Text }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - { name: subtitle, type: string, label: Subtitle }
  - name: team
    label: Team
    path: team
    type: collection
    subfolders: false
    filename: "{primary}.md"
    fields:
      - { name: title, type: string, label: Name }
      - { name: snippet, type: string, label: Role }
      - { name: image, type: image, label: Profile Image }
      - { name: header_image, type: image, label: Header Image }
      - {
          name: body,
          label: Biography,
          type: code,
          options: { language: markdown },
        }
  - name: reviews
    label: Reviews
    path: reviews
    type: collection
    subfolders: false
    fields:
      - { name: name, type: string, label: Name }
      - { name: url, type: string, label: URL }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - name: products
        label: Products
        type: reference
        options:
          collection: products
          multiple: true
          search: "title"
          value: "{path}"
          label: "{title}"
  - name: events
    label: Events
    path: events
    type: collection
    subfolders: false
    filename: "{event_date}-{primary}.md"
    view:
      fields: [title, event_date, event_location]
      primary: title
      sort: [event_date]
    fields:
      - { name: header_image, type: image, label: Header Image }
      - { name: title, type: string, label: Title }
      - { name: subtitle, type: string, label: Subtitle }
      - { name: event_date, label: Event Date, type: date }
      - { name: event_location, type: string, label: Event Location }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - { name: header_text, type: string, label: Header Text }
      - { name: meta_title, type: string, label: Meta Title }
      - { name: meta_description, type: string, label: Meta Description }

  - name: snippets
    label: Snippets
    path: snippets
    type: collection
    subfolders: false
    filename: '{primary}.md'
    fields:
      - { name: name, type: string, label: Name }
      - { name: body, label: Body, type: code, options: { language: markdown } }

  - name: menus
    label: Menus
    path: menus
    type: collection
    subfolders: false
    fields:
      - { name: title, type: string, label: Title }
      - { name: order, type: number, label: Order }
      - { name: header_image, type: image, label: Header Image }
      - { name: description, type: string, label: Description }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - { name: meta_title, type: string, label: Meta Title }
      - { name: meta_description, type: string, label: Meta Description }

  - name: menu-categories
    label: Menu Categories
    path: menu-categories
    type: collection
    subfolders: false
    fields:
      - { name: name, type: string, label: Name }
      - { name: order, type: number, label: Order }
      - name: menus
        label: Menus
        type: reference
        options:
          collection: menus
          multiple: true
          search: "title"
          value: "{path}"
          label: "{title}"
      - { name: body, label: Body, type: code, options: { language: markdown } }

  - name: menu-items
    label: Menu Items
    path: menu-items
    type: collection
    subfolders: false
    fields:
      - { name: name, type: string, label: Name }
      - { name: price, type: string, label: Price }
      - { name: is_vegan, type: boolean, label: Is Vegan }
      - { name: is_gluten_free, type: boolean, label: Is Gluten Free }
      - name: menu_categories
        label: Menu Categories
        type: reference
        options:
          collection: menu-categories
          multiple: true
          search: "name"
          value: "{path}"
          label: "{name}"
      - { name: description, type: string, label: Description }
      - { name: body, label: Body, type: code, options: { language: markdown } }
