name: Build and Deploy

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: chobbledotcom/chobble-client/.github/workflows/shared-build-and-deploy.yml@main
    with:
      bunny-storage-endpoint: "https://uk.storage.bunnycdn.com"
      deploy-only-on-main: true
    secrets: inherit
